# Generated by Django 4.2.5 on 2023-09-13 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('height', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring', models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], max_length=2)),
                ('summer', models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], max_length=2)),
                ('autumn', models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], max_length=2)),
                ('winter', models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('photos', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('1', 'new'), ('2', 'pending'), ('3', 'accepted'), ('4', 'rejected')], default='1', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
                ('coords', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.coords')),
                ('difficulty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.difficultylevels')),
                ('photos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.images')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('id_parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.areas')),
            ],
        ),
    ]
