# Generated by Django 4.2.5 on 2023-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='id_parent',
            field=models.IntegerField(blank=True),
        ),
    ]
