# Generated by Django 4.2.5 on 2023-09-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_areas_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='id_parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.areas'),
        ),
    ]
