# Generated by Django 4.2.5 on 2023-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_areas_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
