# Generated by Django 4.2.5 on 2023-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_users_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='photos',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='autumn',
            field=models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='spring',
            field=models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='summer',
            field=models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='winter',
            field=models.CharField(choices=[('00', 'Неизвестно'), ('1A', '1А'), ('1B', '1Б'), ('2А', '2А'), ('2В', '2Б'), ('3А', '3А'), ('3В', '3Б')], default='00', max_length=2),
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='photos',
        ),
        migrations.DeleteModel(
            name='DifficultyLevels',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='photos',
            field=models.ManyToManyField(blank=True, to='core.images'),
        ),
    ]
