# Generated by Django 4.2.5 on 2023-09-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_photos_images_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
    ]
