# Generated by Django 4.2.5 on 2023-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_beautytitle_perevaladded_beauty_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
